version: "3.7"

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn cmux_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.stage
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - ./.env.stage.db
    restart: always
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
