version: "3.7"

services:
  web:
    build:
      context: ./app
      args:
        requirements: requirements/development.txt
      dockerfile: Dockerfile.prod
    command: gunicorn cmux_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - ./.env.prod.db
  nginx:
    build:
      context: ./nginx
      args:
        conf_file: prod.conf
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
