# Generated by Django 3.0.3 on 2020-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmuxovik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
